name: Giro dâ€™Italia 2022
status: open
maxCyclistsInUserTeam: 12
widgetURL: https://firstcycling.com/widget/?r=13&y=2022&s={stageNumber}&lang=NED
jerseys:
  De Roze Trui: 10
  De Blauwe Trui: 5
scoring:
  - 30
  - 15
  - 12
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  - 3
