---
name: Ronde van het Baskenland 2022
status: open
start: 2022-04-04
maxCyclistsInUserTeam: "12"
externalRankingLink:
  title: Klassement op firstcycling.com
  url: https://firstcycling.com/race.php?r=6&y=2022&e=02
scoring:
  - "50"
  - "40"
  - "20"
  - "10"
  - "5"
