---
name: Tour de France 2022
status: open
start: 2022-07-01
maxCyclistsInUserTeam: 12
widgetURL: https://firstcycling.com/widget/?r=17&y=2022&s={stageNumber}&lang=NED
jerseys:
  De Gele Trui: 10
  De Bolletjes Trui: 5
scoring:
  - 30
  - 15
  - 12
  - 9
  - 5
  - 4
  - 3
  - 2
  - 1
finalStandingScoring:
  - 150
  - 75
  - 50
  - 40
  - 35
  - 30
  - 28
  - 26
  - 24
  - 22
