---
name: Tour de France 2022
status: open
start: 2022-07-01
maxCyclistsInUserTeam: 12
jerseys:
  De Gele Trui: 10
  De Bolletjes Trui: 5
scoring:
  - 30
  - 15
  - 12
  - 9
  - 5
  - 4
  - 3
  - 2
  - 1
